all:
	@echo "Usage: make EXERCISE_NAME"

clean:
	rm -r ./bin

ex1:
	@if [ ! -d ./bin ]; then mkdir bin; fi
	gcc ex1.c -o ./bin/ex1 -no-pie -g

ex2:
	@if [ ! -d ./bin ]; then mkdir bin; fi
	gcc ex2.c -o ./bin/ex2 -no-pie -g


